name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          cp .env.ci .env
          php artisan key:generate

      - name: Set up database
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      - name: Start Laravel server
        run: php artisan serve --host=0.0.0.0 --port=8000 &

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run tests/api_collection.json -e tests/api_environment.json
