on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, ctype, fileinfo, openssl, pdo_mysql, sodium, intl
        coverage: none

    - name: Copy CI Environment
      run: cp .env.ci .env

    - name: Install Dependencies (without scripts)
      run: composer install --prefer-dist --no-progress --no-interaction --no-scripts

    - name: Generate App Key
      run: php artisan key:generate

    - name: Setup Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL
      run: |
        for i in `seq 1 10`;
        do
          mysql -h 127.0.0.1 -uroot -psecret -e 'status' > /dev/null 2>&1 && break
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Create Database
      run: mysql -h 127.0.0.1 -uroot -psecret -e "CREATE DATABASE IF NOT EXISTS laravel_test;"

    - name: Run Migrations
      run: php artisan migrate:fresh --seed

    - name: Run Package Discover
      run: composer run-script post-autoload-dump

    - name: Run API tests with Newman (Postman CLI)
      run: |
        npm install -g newman
        newman run laravel_blog.postman_collection.json 