name: Laravel CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, ctype, fileinfo, openssl, pdo_mysql, sodium, intl
        coverage: none

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Copy CI Environment
      run: cp .env.ci .env

    - name: Generate App Key
      run: php artisan key:generate

    - name: Setup Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mysql -h 127.0.0.1 -uroot -psecret -e "CREATE DATABASE IF NOT EXISTS laravel_test;"
        php artisan migrate:fresh --seed

    - name: Run Tests
      env:
        APP_ENV: ci
      run: php artisan test